:cactus: Setup database and Oauth
astroash/dickhub pull request #9
Opened 2018-01-13 16:39 UTC by ameliejyc

Fixes #3 
📟

2018-01-13 17:53 UTC, astroash requested changes
Also how do you think we should do prs? Do you think we should add small increments of progress or working features (ie when the whole gh login flow is complete). I’m happy either way, I guess it depends whether we are going to do any additional work outside of hangtimes.

2018-01-13 17:53 UTC, astroash commented on package.json
> +    "heroku-postbuild":
Can we set up an eslint config to avoid this in future?

2018-01-13 17:53 UTC, astroash commented on server/server.js
> +      console.log('accessToken', accessToken);
Can we remove the (unworking for I don’t know why 🤷🏽‍♀️) console.logs?

2018-01-14 17:52 UTC, ameliejyc commented on package.json
> +    "heroku-postbuild":
I'm not sure exactly what you mean, please tell me :)

2018-01-14 17:55 UTC, ameliejyc commented
Re flow I think we should do smaller incremental prs so that we can work outside of hangtimes if we wish and still be able to follow everything easily. 

On an unrelated note, are you using prettier? If so we should sync up our configs.

2018-01-14 21:18 UTC, astroash commented on package.json
> +    "heroku-postbuild":
👇 I mean what you said down there! If we set up eslint we will have the same linting configuration so changes like the one ☝️ won't happen. You can setup your prettier so that it's defaults to eslint configs if you have one, if not it uses your prettier config. I made a [handy setup guide](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/linter.md) if you wanna do it.

2018-01-17 19:14 UTC, merged